# Dissecando uma variável
Frase = input('Digite algo: ')
print('O tipo primitvo desse valor é ', end='')
print(type(Frase))
print('Só tem espaços? ', end='')
print(Frase.isspace())
print('É um número? ', end='')
print(Frase.isnumeric())
print('É alfabetico? ', end='')
print(Frase.isalpha())
print('É alfanúmerico? ', end='')
print(Frase.isalnum())
print('Estar em maiúsculas? ', end='')
print(Frase.isupper())
print('Estar em minúsculas? ', end='')
print(Frase.islower())
print('Estar Capitalizada? ', end='')
print(Frase.istitle())
